# This file was generated by swiftpm2nix.
{
  workspaceStateFile = ./workspace-state.json;
  hashes = {
    "AEXML" = "0wpa4fq5dz989d839gs35fspcmhrllin0ckgil7apvwjasmif1vd";
    "GraphViz" = "139g5lb7v9gvxgf19gb66m7vqlsqgbhx0xg91zrvmkdnpzikq0jq";
    "JSONUtilities" = "0l4spypdj6w17vmpgn264gfjxbc02qvvf0qcmgs8br0119z1fpwf";
    "PathKit" = "1zms7zbxmiw5z0s8aj5mhfhji7933wb0p9h6hzbs7fr9b45m633v";
    "Rainbow" = "0iv31azny668vpsjgmldgkgn9cp8i5h9rlc6w5bs8q63nwq19wb0";
    "Spectre" = "0pwr5g3ixj11x50n31235hrxhkj6mwcgnnmwb9xkbyihi124caky";
    "SwiftCLI" = "0zl8s5cg3ama0s1crch0skfbmj3b8pkv42m6rfi5s3rlrcpg6s1y";
    "Version" = "0z2a7qlf05cadmnk5nq3m40d717qb8nnl4jb6gyq3d2nxjai1370";
    "XcodeProj" = "0271a97s0i8yadyb96qdgzsd8sw4dja4w67dsjy01dizrg1ak7xs";
    "Yams" = "11abhcfkmqm3cmh7vp7rqzvxd1zj02j2866a2pp6v9m89456xb76";
  };
}
